blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
                           MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
                           MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView,
                           AttemptListView, AttemptDetailView, index)

app_name = MailingConfig.name

urlpatterns = [
    path('', index, name='index'),
    
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    
    path('attempt_list/', AttemptListView.as_view(), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_detail'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, PasswordResetView, UserProfileDetailView, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_verification'),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    
    path('users/', UserProfileDetailView.as_view(), name='profile'),
    path('users/update/', UserProfileUpdateView.as_view(), name='profile_update'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Заголовок', help_text='Введите заголовок')
    contents_article = models.TextField(max_length=100, verbose_name='Содержимое статьи')
    image = models.ImageField(upload_to="image/blog", blank=True, null=True, verbose_name='Изображения',
                              help_text='Загрузите изображение')
    number_views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров',
                                               help_text="Укажите количество просмотров")
    date_publication = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Статья блога'
        verbose_name_plural = 'Статьи блога'

blog/forms.py
from django import forms
from .models import Blog


class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('name', 'contents_article', 'image', 'number_views', 'date_published')
        

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from blog.models import Blog
from blog.services import get_blog_from_cache


class BlogListView(ListView):
    model = Blog
    
    def get_queryset(self):
        return get_blog_from_cache()
    
    
class BlogDetailView(DetailView):
    model = Blog
    
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('name', 'contents_article', 'image')
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('name', 'contents_article', 'image')
    success_url = reverse_lazy('blog:blog_list')
    
    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>Сервер рассылок для клиентов.</h4>
                <p class="text-body-secondary"></p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Меню</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'mailing:index' %}" class="text-white">Главная</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'mailing:mailing_list' %}" class="text-white">Список рассылок</a></li>
                    <li><a href="{% url 'mailing:client_list' %}" class="text-white">Список клиентов</a></li>
                    <li><a href="{% url 'mailing:attempt_list' %}" class="text-white">Попытки рассылки</a></li>
                    <li><a href="{% url 'blog:blog_list' %}" class="text-white">Список статей</a></li>
                    <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    <li><a href="{% url 'users:password_reset' %}" class="text-white">Забыли пароль</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>