blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
                           MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
                           MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView,
                           AttemptListView, AttemptDetailView, index)

app_name = MailingConfig.name

urlpatterns = [
    path('', index, name='index'),
    
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    
    path('attempt_list/', AttemptListView.as_view(), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_detail'),
]

mailing/forms.py
from django.forms import ModelForm, forms, BooleanField, ModelMultipleChoiceField
from mailing.models import Client, Message, Mailing
from django.forms.widgets import DateTimeInput, SelectMultiple


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
       

class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        widgets = {
            'start_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'type': 'datetime-local'}),
            'next_send_time': DateTimeInput(attrs={'type': 'datetime-local'}),
        }
        message = ModelMultipleChoiceField(queryset=Message.objects.all(),
                                           widget=SelectMultiple(attrs={'class': 'form-control'}))
        client = ModelMultipleChoiceField(queryset=Client.objects.all(),
                                          widget=SelectMultiple(attrs={'class': 'form-control'}))
        
        def clean_client(self):
            client = self.cleaned_data['client']
            if not client:
                raise forms.ValidationError('Требуется клиент')
            return client


class MailingManagerForm(StyleFormMixin, ModelForm):
    """Класс форма для менеджера изменение рассылок."""
    
    class Meta:
        model = Mailing
        fields = ('client', 'message', 'periodicity', 'start_date', 'end_date')


class MailingModeratorForm(StyleFormMixin, ModelForm):
    """Класс форма для модератора изменение рассылок."""
    
    class Meta:
        model = Mailing
        fields = ('client', 'message', 'periodicity', 'start_date', 'end_date')

mailing/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render
from blog.models import Blog
from mailing.forms import ClientForm, MessageForm, MailingForm, MailingManagerForm
from mailing.models import Client, Message, Mailing, Attempt
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.conf import settings
from django.core.exceptions import PermissionDenied

from mailing.task import get_index_from_cache


def index(request):
    """ Обрабатывает запрос на главную страницу сайта. """
    mailing_count = Mailing.objects.count()
    launched_mailing_count = Mailing.objects.filter(status='launched').count()
    unique_clients_count = Mailing.objects.values('client').distinct().count()
    random_articles = Blog.objects.order_by('?')[:3]
    
    context = {
        'mailing_count': mailing_count,
        'launched_mailing_count': launched_mailing_count,
        'unique_clients_count': unique_clients_count,
        'random_articles': random_articles,
    }
    
    if mailing_count == 0 or random_articles.count() == 0:
        context['error_message'] = 'Нет данных для отображения.'
    
    return render(request, 'mailing/index.html', context)
    
    
def get_queryset(self):
    return get_index_from_cache()()


class ClientListView(ListView):
    """ Является представлением списка клиентов. """
    model = Client
    template_name = 'mailing/client_list.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список клиентов'
        return context_data
    
    def get_queryset(self):
        """ Возвращает содержащий только клиентов. """
        return Client.objects.filter(owner=self.request.user)


class ClientDetailView(DetailView):
    """ Является представлением детального просмотра клиента. """
    model = Client
    template_name = 'mailing/client_detail.html'
    
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Информация о клиенте'
        context_data['client'] = self.get_object()
        return context_data


class ClientCreateView(CreateView):
    """ Класс является представлением для создания нового клиента. """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    template_name = 'mailing/client_form.html'
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    """Класс является представлением для обновления информации о клиенте. """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    template_name = 'mailing/client_form.html'
    
    def get_form_class(self):
        """ Метод возвращает класс формы, используемый для обновления информации о клиенте. """
        user = self.request.user
        if user == self.object.owner:
            return ClientForm
        if user.has_perm('client.man_view_the_list_of_service_users') and user.has_perm(
                'client.may_block_users_of_the_service'):
            return MailingManagerForm
        raise PermissionDenied


class ClientDeleteView(DeleteView):
    """ Класс является представлением для удаления клиента. """
    model = Client
    success_url = reverse_lazy('mailing:client_list')
    template_name = 'mailing/client_confirm_delete.html'


class MessageListView(ListView):
    """ Класс является представлением списка писем. """
    model = Message
    template_name = 'mailing/message_list.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список писем'
        return context_data
    
    def get_queryset(self):
        """ Возвращает содержащие только письма текущего пользователя. """
        return Message.objects.filter(owner=self.request.user)


class MessageDetailView(DetailView):
    """ Класс является представлением детального просмотра письма. """
    model = Message
    template_name = 'mailing/message_detail.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Информация о письме'
        return context_data


class MessageCreateView(CreateView):
    """ Класс является представлением для создания нового письма. """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')
    template_name = 'mailing/message_form.html'
    
    def form_valid(self, form):
        """ Метод присваивает владельца создаваемому объекту. """
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    """ Класс является представлением для обновления информации о письме. """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')
    template_name = 'mailing/message_form.html'
    
    def form_valid(self, form):
        """ Метод проверяет, что письмо не уже входит в рассылку. """
        message_id = form.cleaned_data['message']
        if Mailing.objects.filter(message=message_id).exists():
            pass
        else:
            return super().form_valid(form)
    
    def get_form_class(self):
        """ Метод возвращает класс формы, используемый для обновления информации о письме. """
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        if user.has_perm('message.can_view_messages') and user.has_perm(
                'message.can_edit_messages'):
            return MailingManagerForm
        raise PermissionDenied


class MessageDeleteView(DeleteView):
    """ Класс является представлением для удаления письма. """
    model = Message
    success_url = reverse_lazy('mailing:message_list')
    template_name = 'mailing/message_confirm_delete.html'


class MailingListView(ListView):
    """ Класс является представлением списка рассылок. """
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список рассылок'
        return context_data
    
    def get_queryset(self):
        """ Возвращает содержащие только рассылки текущего пользователя. """
        return Mailing.objects.filter(owner=self.request.user)


class MailingDetailView(DetailView):
    """ Класс является представлением детального просмотра рассылки. """
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Информация о рассылки'
        return context_data


class MailingCreateView(CreateView):
    """ Класс является представлением для создания нового рассылки. """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')
    template_name = 'mailing/mailing_form.html'
    
    def form_valid(self, form):
        """ Метод присваивает владельца создаваемому объекту. """
        form.instance.owner = self.request.user
        message = form.cleaned_data['message']
        subject_of_the_letter = message.subject_of_the_letter
        body_of_the_letter = message.body_of_the_letter
        email_from = settings.EMAIL_HOST_USER
        client = form.cleaned_data['client']
        email = [client.email, ]
        
        try:
            send_mail(subject_of_the_letter, body_of_the_letter, email_from, email)
        except BadHeaderError:
            return HttpResponse('Ошибка отправки.')
        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    """ Класс является представлением для обновления информации о рассылке. """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')
    template_name = 'mailing/mailing_form.html'
    
    def get_form_class(self):
        """ Метод возвращает класс формы, используемый для обновления информации о рассылке. """
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        if user.has_perm('mailing.can_view_any_mailings') and user.has_perm(
                'mailing.can_disable_mailings'):
            return MailingManagerForm
        raise PermissionDenied


class MailingDeleteView(DeleteView):
    """ Класс является представлением для удаления рассылки. """
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')
    template_name = 'mailing/mailing_confirm_delete.html'


class AttemptListView(ListView):
    """ Класс является представлением списка попыток рассылки. """
    model = Attempt
    template_name = 'mailing/attempt_list.html'
    
    def get_context_data(self, **kwargs):
        """ Метод формирует контекст для шаблона. """
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список попыток'
        return context_data


class AttemptDetailView(DetailView):
    """ Класс является представлением для отображения детальной информации о попытке рассылки. """
    model = Attempt
    template_name = 'mailing/attempt_detail.html'
    
    def get_context_data(self, **kwargs):
        """ Метод возвращает контекст для шаблона отображения детальной информации о попытке рассылки. """

mailing/templates/mailing/attempt_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm-4">
                <div class="card-body">
                    <p class="card-text">Дата последней попытки:{% if attempt.date_last_attempt %}
                        {{attempt.date_last_attempt|date:"d-m-Y H:i"}}
                        {% else %}
                        Не обнаружена дата попытки!
                        {% endif %}</p>
                    <p class="card-text">Время последней попытки:{% if attempt.time_last_attempt %}
                        {{attempt.time_last_attempt}}
                        {% else %}
                        Не обнаружена время попытки!
                        {% endif %}</p>
                    <p class="card-text">Ответ почтового сервера, если он был:{% if attempt.response %}
                        {{attempt.response}}
                        {% else %}
                        Нет ответа почтового сервера.
                        {% endif %}</p>
                    <p class="card-text">Статус попытки: {{attempt.attempt_status}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailing:attempt_list' %}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="cards">
                    <p class="card-text">Действительно хотите удалить {{object.name}}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'mailing:client_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm-4">
                <div class="card-body">
                    <p class="card-text">Контактный email: {{client.email}}</p>
                    <p class="card-text">Фамилия: {{client.last_name}}</p>
                    <p class="card-text">Имя: {{client.first_name}}</p>
                    <p class="card-text">Отчество: {{client.patronymic}}</p>
                    <p class="card-text">Комментарий: {{client.comment}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailing:client_list' %}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h1>{{title}}</h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for client in client_list %}
            <div class="col">
                <div class="card shadow-sm-4">
                    <div class="card-body">
                        <p class="card-text">Контактный email: {{client.email}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-success" href="{% url 'mailing:client_detail' client.pk %}"
                                   role="button">Подробнее</a>
                                {% if user.is_authenticated == user.owner %}
                                <a class="btn btn-warning" href="{% url 'mailing:client_update' client.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'mailing:client_delete' client.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block content %}
  <h1>Главная страница</h1>
  <div class="row">
    <div class="col-md-4">
      <h2>Статистика рассылок</h2>
      <ul>
        <li>Количество рассылок всего: {{mailing_count}}</li>
        <li>Количество активных рассылок: {{launched_mailing_count}}</li>
        <li>Количество уникальных клиентов для рассылок: {{unique_clients_count}}</li>
      </ul>
    </div>
    <div class="col-md-8">
      <h2>Случайные статьи из блога</h2>
      <ul>
        {% for article in random_articles %}
          <li>
            <h3>{{ article.name }}</h3>
            <p>{{ article.contents_article|truncatewords:50 }}</p>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="cards">
                    <p class="card-text">Действительно хотите удалить {{object.name}}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm-4">
                <div class="card-body">
                    <p class="card-text">Дата и время начала рассылки:{{mailing.start_date}}</p>
                    <p class="card-text">Дата и время окончания рассылки:{{mailing.end_date}}</p>
                    <p class="card-text">Дата и время следующей отправки рассылки:{{mailing.next_send_time}}</p>
                    <p class="card-text">Периодичность рассылки письма: {{mailing.periodicity}}</p>
                    <p class="card-text">Статус рассылки: {{mailing.status}}</p>
                    <p class="card-text">Сообщение: {{mailing.message}}</p>
                    <p class="card-text">Клиенты рассылки: {{ mailing.client.name }} ({{ mailing.client.email }})</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="album py-5 bg-body-tertiary">
        <div class="row-2">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<a href="{% url 'mailing:message_create' %}" class="btn btn-primary-sm-4">Создать сообщение</a>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for mailing in mailing_list %}
            <div class="col">
                <div class="card shadow-sm-4">
                    <div class="card-body">
                        <p class="card-text">Дата и время начала рассылки: {{mailing.start_date}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-success" href="{% url 'mailing:mailing_detail' mailing.pk %}"
                                   role="button">Подробнее</a>
                                {% if user.is_authenticated == user.owner %}
                                <a class="btn btn-warning" href="{% url 'mailing:mailing_update' mailing.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="cards">
                    <p class="card-text">Действительно хотите удалить {{object.name}}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm-4">
                <div class="card-body">
                    <p class="card-text">Тема письма: {{message.subject_of_the_letter}}</p>
                    <p class="card-text">Тело письма: {{message.body_of_the_letter}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailing:message_list' %}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="album py-5 bg-body-tertiary">
        <div class="row-2">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<a href="{% url 'mailing:message_create' %}" class="btn btn-primary-sm-4">Создать сообщение</a>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for message in message_list %}
            <div class="col">
                <div class="card shadow-sm-4">
                    <div class="card-body">
                        <p class="card-text">Тема письма: {{message.subject_of_the_letter}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-success" href="{% url 'mailing:message_detail' message.pk %}"
                                   role="button">Подробнее</a>
                                {% if user.is_authenticated == user.owner %}
                                <a class="btn btn-warning" href="{% url 'mailing:message_update' message.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'mailing:message_delete' message.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}