blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, PasswordResetView, UserProfileDetailView, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_verification'),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    
    path('users/', UserProfileDetailView.as_view(), name='profile'),
    path('users/update/', UserProfileUpdateView.as_view(), name='profile_update'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    
    avatar = models.ImageField(upload_to='users/avatars', blank=True, null=True, verbose_name='Аватар',
                               help_text='Загрузите аватар')
    phone_number = models.CharField(max_length=35, verbose_name='Номер телефона', blank=True, null=True,
                                    help_text='Введите номер телефона')
    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
    
    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from mailing.forms import StyleFormMixin
from users.models import User
from django.forms import ModelForm


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Класс форма для пользователя"""
    
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        
        
class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'avatar', 'phone_number', 'token']

users/views.py
import secrets
import string
import random

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView
from django.views import View

from users.forms import UserRegisterForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    """Класс-контроллер для создания нового пользователя"""
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        user.token = token
        user.save()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Здравствуйте, перейдите по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class PasswordResetView(View):
    """Класс-контроллер для восстановления пароля"""
    form_class = PasswordResetForm
    template_name = 'users/password_reset.html'
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
                new_password = ''.join(
                    random.choices(string.ascii_letters + string.digits, k=8)
                )
                user.password = make_password(new_password)
                user.save()
                
                send_mail(
                    subject='Восстановление пароля',
                    message=f'Введите новый пароль: {new_password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[email],
                )
                return redirect(reverse('users:login'))
            except User.DoesNotExist:
                form.add_error('email', 'Пользователь с таким email не найден')
        return render(request, self.template_name, {'form': form})


class UserProfileDetailView(DetailView):
    """ """
    model = User
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user


class UserProfileUpdateView(UpdateView):
    """  """
    model = User
    fields = ['email', 'first_name', 'last_name', 'avatar', 'phone_number']
    template_name = 'users/profile_form.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/password_reset.html
{% extends "mailing/base.html" %}
{% block content %}
<h2>Восстановление пароля</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Восстановить пароль</button>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="container">
    <h1 class="text-center">Профиль пользователя</h1>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <table class="table table-striped">
          <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
          </tr>
          <tr>
            <th>Имя</th>
            <td>{{ user.first_name }}</td>
          </tr>
          <tr>
            <th>Фамилия</th>
            <td>{{ user.last_name }}</td>
          </tr>
          <tr>
            <th>Аватар</th>
            <td>
              {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Аватар" class="img-thumbnail">
              {% else %}
                Нет аватара
              {% endif %}
            </td>
          </tr>
          <tr>
            <th>Номер телефона</th>
            <td>{{ user.phone_number }}</td>
          </tr>
          <tr>
            <th>Token</th>
            <td>{{ user.token }}</td>
          </tr>
        </table>
        <p class="text-center">
          <a href="{% url 'users:profile_update' %}" class="btn btn-primary">Обновить профиль</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/profile_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row text-center">
            Редактирование профиля
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">
            Обновить профиль
        </button>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row text-center">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success">
            Зарегистрироваться
        </button>
    </form>
</div>
{% endblock %}